### ISSUE TITLE
Proxy DC/OS metrics

### ISSUE THREAD

**Issue by mwl** [humio/dcos2humio#3]
https://github.com/dcos/dcos-metrics

**Comment by ssiahetiong** [comment]
Use metricbeat [http module](https://www.elastic.co/guide/en/beats/metricbeat/master/metricbeat-module-http.html) to poll dcos-metrics. See #3

**Comment by mwl** [comment]
Nope, I didn't know about that. Thanks a lot! Also, you are more than welcome to reach out to me on our community Slack, http://community.humio.com

**Comment by mwl** [comment]
This has somewhat been sorted in #17, but since support for EE is limited I'll leave it open until Mesosphere comes back with an answer on wether they'll allow unauthenticated access to the metrics endpoint on localhost.
